### ISSUE TITLE
Where can i get Telegram API keys ?

### ISSUE THREAD

**Issue by Deconta** [kokiez/solana-sniper#1]
I have the Alert Channels form bonk bot how can i use them ?

**Comment by kokiez** [comment]
https://core.telegram.org/api/obtaining_api_id

**Comment by Deconta** [comment]
Cool, I'll try it out.  So can I use the signals that are posted in the bonk bot?  Have you already had experience with your bot and made a profit?  First of all, thanks for sharing.

**Comment by kokiez** [comment]
yes and it is better than bonk bot.

**Comment by Deconta** [comment]
Sorry for asking so many questions. But I would like to test your bot and somehow I can't get it to work. What do I have to enter here after executing if I get this message? Please enter your phone (or bot token): ?
Do I have to create my own alert bot? Can you help me set it up? Thanks

**Comment by kokiez** [comment]
dm on discord

**Comment by Deconta** [comment]
Unfortunately I can't add you to discord. 
Can you add me: locosjulian

greeting
