### ISSUE TITLE
What parameter to modify to increase the fees?

### ISSUE THREAD

**Issue by nicolasviegas** [kokiez/solana-sniper#12]
I want to increase the amount of fees to speed up transactions.

In the 'amm_selection' file the following parameter is found
` miniumBalanceRequired = 10000000 #for txn fees etc`

I have to modify that?

**Comment by kokiez** [comment]
Thats the default fees for a txn which I had initially implemented for Jupiter api and also the bot will not execute trades when the test wallet balance goes under 0.01 SOL.

The raydium code does not implement any methods for fees but you may further read about it in [solders library](https://kevinheavey.github.io/solders/api_reference/compute_budget.html)
