### ISSUE TITLE
PnL execution Question

### ISSUE THREAD

**Issue by CryptoX78** [kokiez/solana-sniper#15]
Hi, Thank you for developing and sharing this project, It’s been a great help building my Python knowledge.

I just wanted to ask why I received less sol when the bot sold the trade at a profit. I know It’s a test-size trade, but the profit should’ve easily more than covered the sol commissions. Maybe I’m overlooking something? I’ve attached screenshots.
![IMG_1416](https://github.com/kokiez/solana-sniper/assets/155875257/9c509c00-00f4-4f51-9235-8de229419558)
![IMG_1417](https://github.com/kokiez/solana-sniper/assets/155875257/570aac9e-9e15-4c3c-a2bb-950acba1d9fc)
![IMG_1418](https://github.com/kokiez/solana-sniper/assets/155875257/d83bf3ef-c3c5-4749-8925-3e64f7cc24b8)

Cheers.

**Comment by CryptoX78** [comment]
Looking further into the above, think it may just relate to slippage. Think I may’ve been sandwiched a few times!

**Comment by kokiez** [comment]
price difference.
price was detected.
6 seconds later txn was confirmed.
