### ISSUE TITLE
Lack of setting slippage in raydium/buy_swap.py

### ISSUE THREAD

**Issue by honhantri1995** [kokiez/solana-sniper#18]
In file "raydium/buy_swap.py", I see that you DID NOT set slippage when sending the transaction.

Can I ask why?

I think setting slippage is very necessary.

Thanks and best regards.

**Comment by kokiez** [comment]
setting slippage will result in txn drop when you are trading low lp coins.
have you not noticed this on the raydium site?

**Comment by honhantri1995** [comment]
On the Raydium site, I still set slippage.
I think setting 50% slippage won't cause drop txn in most cases.
