### ISSUE TITLE
Problem with installing requirements 

### ISSUE THREAD

**Issue by sindri55** [kokiez/solana-sniper#2]
Btw. Great work, been looking this for few days now. Excited to try it out.

Im running Python 3.9.6 and pip 23.3.2 in VS
also tried the newest version with python3.
Macbook pro 2017
What is this error, do you know? 

sindri@Sindris-MacBook-Pro solana-sniper % pip install -r requirements.txt
Collecting base58==2.1.1 (from -r requirements.txt (line 1))
  Using cached base58-2.1.1-py3-none-any.whl (5.6 kB)
Collecting construct==2.10.68 (from -r requirements.txt (line 2))
  Using cached construct-2.10.68.tar.gz (57 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Requests==2.31.0 (from -r requirements.txt (line 3))
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting solana==0.30.2 (from -r requirements.txt (line 4))
  Using cached solana-0.30.2-py3-none-any.whl.metadata (5.2 kB)
Collecting solders==0.18.1 (from -r requirements.txt (line 5))
  Using cached solders-0.18.1-cp37-abi3-macosx_10_9_x86_64.macosx_11_0_arm64.macosx_10_9_universal2.whl.metadata (3.8 kB)
Collecting spl==0.0.1.dev0 (from -r requirements.txt (line 6))
  Using cached spl-0.0.1.dev0.tar.gz (6.3 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Telethon==1.33.0 (from -r requirements.txt (line 7))
  Using cached Telethon-1.33.0.tar.gz (568 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting charset-normalizer<4,>=2 (from Requests==2.31.0->-r requirements.txt (line 3))
  Using cached charset_normalizer-3.3.2-cp312-cp312-macosx_10_9_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from Requests==2.31.0->-r requirements.txt (line 3))
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from Requests==2.31.0->-r requirements.txt (line 3))
  Using cached urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from Requests==2.31.0->-r requirements.txt (line 3))
  Using cached certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting cachetools<5.0.0,>=4.2.2 (from solana==0.30.2->-r requirements.txt (line 4))
  Using cached cachetools-4.2.4-py3-none-any.whl (10 kB)
Collecting construct-typing<0.6.0,>=0.5.2 (from solana==0.30.2->-r requirements.txt (line 4))
  Using cached construct_typing-0.5.6-py3-none-any.whl (24 kB)
Collecting httpx<0.24.0,>=0.23.0 (from solana==0.30.2->-r requirements.txt (line 4))
  Using cached httpx-0.23.3-py3-none-any.whl (71 kB)
Collecting types-cachetools<5.0.0,>=4.2.4 (from solana==0.30.2->-r requirements.txt (line 4))
  Using cached types_cachetools-4.2.10-py3-none-any.whl (4.8 kB)
Collecting typing-extensions>=4.2.0 (from solana==0.30.2->-r requirements.txt (line 4))
  Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting websockets<12.0,>=9.0 (from solana==0.30.2->-r requirements.txt (line 4))
  Using cached websockets-11.0.3-py3-none-any.whl (118 kB)
Collecting jsonalias==0.1.1 (from solders==0.18.1->-r requirements.txt (line 5))
  Using cached jsonalias-0.1.1-py3-none-any.whl (1.3 kB)
Collecting bunch (from spl==0.0.1.dev0->-r requirements.txt (line 6))
  Using cached bunch-1.0.1.zip (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_s/wzjvzln17m3fm1b28mk_sy_80000gn/T/pip-build-env-pm9d85n5/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_s/wzjvzln17m3fm1b28mk_sy_80000gn/T/pip-build-env-pm9d85n5/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/_s/wzjvzln17m3fm1b28mk_sy_80000gn/T/pip-build-env-pm9d85n5/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/_s/wzjvzln17m3fm1b28mk_sy_80000gn/T/pip-build-env-pm9d85n5/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      ValueError: invalid mode: 'rU'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
sindri@Sindris-MacBook-Pro solana-sniper %

**Comment by sindri55** [comment]
Also changed to Python3 3.12.1, and pip3 install -r requirements.txt     
Happens the same.

**Comment by sindri55** [comment]
All in VS

**Comment by kokiez** [comment]
no clue, google says: pip install wheel

**Comment by sindri55** [comment]
I installed the "spl" alone and commented it in the config file. is working well now. Very much appreciated, been looking for this for few days now 🙌

**Comment by sindri55** [comment]
If you want to collaborate on this project or brainstorm, hit me up on TG @BBunnyToken
