### ISSUE TITLE
missing basic config.ini contents!

### ISSUE THREAD

**Issue by aayasmin** [kokiez/solana-sniper#3]
I ran your code, installed the module then filled in the pk and rpc but the application didn't respond anything.
![Cuplikan layar 2023-12-29 063331](https://github.com/kokiez/solana-sniper/assets/154961707/a314b02d-543f-4955-bae3-e210c15978c0)

here are the logs
![image](https://github.com/kokiez/solana-sniper/assets/154961707/6b4368aa-f1a2-4745-b50f-2ec35516a656)

should I fill this in?
![image](https://github.com/kokiez/solana-sniper/assets/154961707/57cb2b7b-e8da-4abe-96b2-10d587c7d7ca)
Can you help me ?

**Comment by kokiez** [comment]
Please read readme and complete config.ini. 
You cannot expect the sniper to function on its own and snipe tokens without you providing it instructions. 
It is something like you are starting a car without its key or theft knowledge or without its tyres, So please complete config.ini and always read readme...

**Comment by aayasmin** [comment]
![image](https://github.com/kokiez/solana-sniper/assets/154961707/fc17cbee-3e7a-4775-9c19-0dc9f651fe13)
Can you give me an example to fill this in? I'm confused about this part of Telegram

**Comment by aayasmin** [comment]
![image](https://github.com/kokiez/solana-sniper/assets/154961707/b0a0ae88-dfe7-4498-a99f-bb5a9a1a4e39)
OK, I just read it
