### ISSUE TITLE
Can I deactivate the Jupyter Swap option to get faster swaps?

### ISSUE THREAD

**Issue by nicolasviegas** [kokiez/solana-sniper#9]
Hi, I'm using the project, and it's awesome, thanks for your work.

I use to buy low liquidity tokens, as I see in your comments, Jupyter doesn't work with low liquidity tokens, so instead the script use Raydium.

```
  if Jupiter fails, then try Raydium
                (if you intrested why? read more about it in docs, liquidity and why some coins are not added to jupiter)

                Raydium Swap Starts here

                Just use Raydium man, its much faster and better than Jupiter because of liquidity
                But issue is that if pair is new then pools gonna be downloaded again... which slows the transaction by 10 seconds
```
               
I don't understand the final comment, if I delete the Jupyter swap it's going to be slower than if not?

**Comment by kokiez** [comment]
https://github.com/kokiez/solana-sniper/blob/main/raydium/create_close_account.py#L94C29-L94C29

I am downloading the pools. 
if you are sniping pre-launch tokens, it wont work! Else it will work

**Comment by nicolasviegas** [comment]
Did you know what this error mean when selling: 

[Raydium]: 'NoneType' object has no attribute 'transaction'
